"""First migration

Revision ID: 48a400bc986f
Revises:
Create Date: 2023-06-07 20:59:48.395540

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "48a400bc986f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("id", sa.String(length=14), nullable=False),
        sa.Column("last_modified", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("other_names", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_activities_id"), "activities", ["id"], unique=False)
    op.create_table(
        "completed_activities",
        sa.Column("id", sa.String(length=14), nullable=False),
        sa.Column("last_modified", sa.DateTime(), nullable=False),
        sa.Column("activity_id", sa.String(length=14), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column(
            "intensity",
            sa.Enum("low", "medium", "high", name="intensity"),
            nullable=False,
        ),
        sa.Column(
            "duration",
            sa.Enum("short", "medium", "long", name="duration"),
            nullable=False,
        ),
        sa.Column("notes", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_completed_activities_id"), "completed_activities", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_completed_activities_id"), table_name="completed_activities")
    op.drop_table("completed_activities")
    op.drop_index(op.f("ix_activities_id"), table_name="activities")
    op.drop_table("activities")
    # ### end Alembic commands ###
