version: "3.4"

services:
  fitness-tracker-webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    image: fitness-tracker-webapp
    container_name: fitness-tracker-webapp
    command: "npm start"
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
      - REACT_APP_API_ADMIN_SECRET=${REACT_APP_API_ADMIN_SECRET}
    volumes:
      - ./webapp:/app

      # create an empty directory at `/app/node_modules` instead of using the previously
      # mounted `./webapp/node_modules` directory, so the host's `node_modules` ownership
      # doesn't pass to the container's user
      - /app/node_modules
      # These volumes are not present when building the image, so the `node_modules`
      # folder will not show up in the host until you run the container
      # https://stackoverflow.com/a/32785014

  qr:
    build:
      context: ./qr
      dockerfile: Dockerfile
    image: qr
    container_name: qr
    volumes:
      - ./qr:/app
