version: "3.8"

services:
  fitness-tracker-webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    image: fitness-tracker-webapp
    container_name: fitness-tracker-webapp
    command: "npm start"
    ports:
      - "3000:3000"
    # environment:
    #   - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
    #   - REACT_APP_API_ADMIN_SECRET=${REACT_APP_API_ADMIN_SECRET}
    volumes:
      - ./webapp:/app

      # create an empty directory at `/app/node_modules` instead of using the previously
      # mounted `./webapp/node_modules` directory, so the host's `node_modules` ownership
      # doesn't pass to the container's user
      - /app/node_modules

  qr:
    build:
      context: ./qr
      dockerfile: Dockerfile
    image: qr
    container_name: qr
    volumes:
      - ./qr:/app

  fitness-tracker-api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        USER_ID: "${UID}"
        GROUP_ID: "${GID}"
    image: fitness-tracker-api
    container_name: fitness-tracker-api
    user: "${UID}:${GID}"
    environment:
      - USER_ID="${UID}"
      - GROUP_ID="${GID}"
    volumes:
      - ./api:/app

  fitness-tracker-api-root:
    extends:
      service: fitness-tracker-api
    user: "0:0"
