services:

  fitness-tracker-webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    image: fitness-tracker-webapp
    container_name: fitness-tracker-webapp
    command: "npm start"
    ports:
      - "3000:3000"
    volumes:
      - ./webapp:/app

      # create an empty directory at `/app/node_modules` instead of using the previously
      # mounted `./webapp/node_modules` directory, so the host's `node_modules` ownership
      # doesn't pass to the container's user
      - /app/node_modules

  fitness-tracker-webapp-ngrok:
    image: ngrok/ngrok:latest
    container_name: fitness-tracker-webapp-ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
